### ISSUE TITLE
[1.12.2] Crash with Forestry

### ISSUE THREAD

**Issue by MasterEnderman** [Elecs-Mods/ElecCore#122] opened 2017-11-04 00:26 UTC
Forge: 14.23.0.2522
ElecCore: 1.8.430
Forestry: 5.7.0.209
Crash-Report: https://pastebin.com/FH48LGyU

**Comment by Staegrin** [comment] 2017-11-04 10:55
Downgrading Forestry to version 5.6.0.201 seems to be a good temporary workaround.

**Comment by MasterEnderman** [comment] 2017-11-04 12:56
But the 5.6.0.201 doesn't have the new module config system. Guess I have to turn ElecCore off for now.

**Comment by carstorm** [comment] 2017-11-04 18:32
If it helps at all, I'm having the same issue https://pastebin.com/aajxC95R

For now, I downgraded forestry though I hope the issue is resolved soon.

**Comment by Tencao** [comment] 2017-11-05 01:38
I've fixed this in a PR, #123 . Just need to wait for it to be pulled or for them to fix it themselves.

**Comment by madhatr** [comment] 2017-11-12 18:26
When's that pull request going to get in?  Disabling ElecCore and DR for now.

**Comment by Tencao** [comment] 2017-11-15 16:41
@madhatr The pull request was recently merged, so hopefully not long before it's released on curse

**Comment by Elec332** [comment] 2017-11-15 20:58
Uploaded

**Closed as completed by Elec332** 2017-11-15 20:58 UTC
