### ISSUE TITLE
Forge *2063 world load hang (NPE)

### ISSUE THREAD

**Issue by Anarcraft** [Elecs-Mods/ElecCore#52] opened 2016-08-14 18:47 UTC
The world hangs forever on load in single player after upgrading from forge 12.18.1.2061 to 12.18.1.2063.  This is with ElecCore-1.9.4-1.5.303.  It worked for sure at least once after upgrading, maybe twice?  After which it would just hang everytime.

Backdating to forge 2061 resolves the issue.

The part from latest.log
http://pastebin.com/AZGp2tnG

**Comment by Elec332** [comment] 2016-08-17 08:02
Can I please have the entire log?

**Comment by lilmoefow** [comment] 2016-08-23 17:27
I am having this same issue on Forge 2073  Instead of opening a new issue i am going to just give my full log here.. hopefully it will help.

https://gist.github.com/lilmoefow/c4e33088ab5d80fce2aa0e29013b0f11

**Comment by mezz** [comment] 2016-09-27 22:21
I got the same error. Here's the full log: https://gist.github.com/mezz/d60afe2ba1e4d647cb2831b565faa6dc
Something in my dev environment crashed while I was loading a world, and then the eleccore onWorldSave handler crashed and caused the game to hang forever.

**Comment by Elec332** [comment] 2016-09-28 14:23
Because of this: http://prntscr.com/cndsx8, MC crashes before a WorldLoadEvent has been fired.
This causes a NBT tag to be null when the WorldUnloadEvent gets fired, which causes a NPE.

**Comment by Elec332** [comment] 2016-10-15 07:27
Closing as the root cause is not ElecCore

**Closed as completed by Elec332** 2016-10-15 07:27 UTC
Labels: bug

**Comment by mezz** [comment] 2016-10-15 07:31
I believe ElecCore will cause the game to hang when _any_ mod crashes during world load. Please protect against this case, it makes it much harder to figure out what's actually crashing.

**Comment by Elec332** [comment] 2016-10-15 07:32
I will add a protection for this

**Comment by Elec332** [comment] 2016-10-15 07:34
Seems like I already did that a few versions ago :P
https://github.com/Elecs-Mods/ElecCore/commit/00e5f4f15ab95012449fcdf13a82c03d83f465d9
