### ISSUE TITLE
Console Spam 

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/ElecCore#47] opened 2016-07-03 15:05 UTC
Keep getting spammed the same lines continually 

`[06:26:35] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:118]: ------------------------------------
[06:26:35] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:116]: ------------------------------------
[06:26:35] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:117]: ERROR!!!  Tile at BlockPos{x=-79, y=65, z=1524} is trying to register whilst already being registered!
[06:26:35] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:118]: ------------------------------------`

ElecCore Version: ElecCore-1.9.4-1.5.292

**Comment by Gunner76th** [comment] 2016-07-04 14:28
This is a duplicate of issue https://github.com/Elecs-Mods/ElecCore/issues/37

This is happening with release version 1.5.292 for Minecraft 1.9.4

**Comment by Gunner76th** [comment] 2016-07-04 14:42
This is also a duplicate of this issue reported in Deep Resonance https://github.com/McJty/DeepResonance/issues/68

This issue is causing excessively large console log files which, on servers that have limited storage space, could lead to storage space depletion and total server corruption. The average rate of spam to the console is 1 message set every 15-30 seconds (varies within that range), and current average console log file size is 90 megs in size. Below is a sample output of the current spam from version 292 of Elec-Core.

[10:41:52] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:95]: Something weird was detected, fixing now...
[10:41:52] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:116]: ------------------------------------
[10:41:52] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:117]: ERROR!!!  Tile at BlockPos{x=-7, y=66, z=-178} is trying to register whilst already being registered!
[10:41:52] [Server thread/INFO] [STDOUT]: [elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:118]: ------------------------------------

**Comment by Gunner76th** [comment] 2016-07-04 15:28
On my server, currently the console spam is becaused by a set of Deep Resonance tanks (#6105) that are stacked together, 3 high, all filled with lava. As long as the area is chunk loaded, there is no issue, however, once the chunk unloads the console begins to spam about the block. Also this only happens when the chunk is loaded and then unloads, as it does not occur after a server restart and the chunk is not initially loaded. 

The tanks in question are in a single column 3 high, all full of lava, placed touching a Tcon smeltery, with the tank blocks only touching seared stone (#8745/0) blocks. 

Server restart, chunk no loaded = no spam
Player visits area, remains in area and chunk is loaded = no spam
Chunk loader active in chunk, player visits then leaves = no spam
Player visits area, causing chunk to load, then leaves chunk causing chunk to unload = spam

Based on this testing, the issue in question is directly tied to some sort of chunk access method that is failing or having an issue when a chunk is not loaded.

**Comment by Elec332** [comment] 2016-07-05 15:40
Yes, but im closing this because this already has an ticket on the DeepResonance repo

**Closed as completed by Elec332** 2016-07-05 15:40 UTC
