### ISSUE TITLE
Crash with the new version of forge

### ISSUE THREAD

**Issue by ghost** [Elecs-Mods/ElecCore#125] opened 2017-11-09 02:12 UTC
https://gist.github.com/xKnightGamingx/8fcdae26f968cf420e7ac3272e296cb2

**Comment by SnowShock35** [comment] 2017-11-09 14:07
Crash is with newer Forestry not Forge. The likelihood a bug is broken because of Forge is highly unlikely especially when there's already like 100 other mods loaded. 😉

Therefore, duplicate of #122

**Comment by SethWilliamson** [comment] 2017-11-11 05:55
Runs fine with Forge 14.23.0.2537, MC 1.12.2

**Comment by Elec332** [comment] 2017-11-15 20:59
Fixed, and yes, this was an incompatibility with the latest Forestry versions.

**Closed as completed by Elec332** 2017-11-15 20:59 UTC
